TECH: Add tooltip to help describe fields
smartrent/badmagic pull request #47
Opened 2021-04-17 00:56 UTC by tmadar

Add a `tooltip` by input fields that pulls from the `description` attribute to help explain ambiguous sounding fields

![image](https://user-images.githubusercontent.com/1951558/115096840-cbd9b100-9edb-11eb-8c05-c418dbd8b18d.png)

Help to address feedback about a certain field faster than digging through the documentations tab

![image](https://user-images.githubusercontent.com/1951558/115097075-f415df80-9edc-11eb-8928-87ae0879affc.png)

2021-04-17 01:18 UTC, matthew-kerle commented
Oh nice! I was just thinking about talking to Jason about something like this actually the other day.

2021-04-19 19:13 UTC, bjyoungblood requested changes

2021-04-19 19:13 UTC, bjyoungblood commented on package.json
> +    "@material-ui/core": "4.11.3",
As much as I hardcore material-ui (and I really, really do), [`rc-tooltip`](https://github.com/react-component/tooltip) is a lot lighter, and we already package it with other projects.

2021-04-19 19:13 UTC, bjyoungblood commented on src/types.ts
> +  tooltip?: boolean;
Looking at the code, it seems like if `tooltip` is false, we don't render `description` at all. Is that accurate? If that's the case, then could we just render the tooltip if `description` is not false-y? If not, then what do you think of changing tooltip to a string and treating it separately from `description`?

2021-04-19 21:54 UTC, tmadar commented on src/types.ts
> +  tooltip?: boolean;
i agree. @jwdotjs walked me through that we want the attributes to follow similar to OpenApiSpex, so I can simplify things and just check if a description is provided for deciding to render.

2021-04-19 21:54 UTC, tmadar commented on package.json
> +    "@material-ui/core": "4.11.3",
nice! I'll take a look at `rc-tooltip`. i used material-ui as its what I'm used to using in other projects

2021-04-24 15:36 UTC, tmadar commented on package.json
> +    "@material-ui/core": "4.11.3",
Been trying to update to use `rc-tooltip` over material-ui and having a bear of a time trying to implement it without introducing my own sort of state management. I hover / click - the text shows - then clicking or unhovering doesnt cause it to disappear. Same sort of behavior found in this person's code sandbox from SO https://stackoverflow.com/questions/63628698/react-rc-tooltips-tooltips-wont-hide-after-state-changes

2021-04-24 16:20 UTC, tmadar commented
Replace material-ui with rc-tooltip per @bjyoungblood suggestion and brought in the `help` icon from the js-shared icons. The component styling was borrowed from CMW `assets/js/react/common/HoverText.tsx`. I think maybe the icon component needs some changing in here because the fill-color looks off

![Screen Shot 2021-04-24 at 9 16 08 AM](https://user-images.githubusercontent.com/1951558/115965383-e1ec0080-a4dd-11eb-9ac6-6678c88f6bee.png)

2021-04-26 19:50 UTC, bjyoungblood reviewed
Looking good. I think you just need to run `yarn prettier --write ./src` and it'll get a ✅  from me!

> I think maybe the icon component needs some changing in here because the fill-color looks off.

I think that might just be [how the icon looks](https://smartrent-ui.com/icons). 😕

2021-04-26 19:50 UTC, bjyoungblood commented on package.json
> +    "rc-tooltip": "5.1.0",
```suggestion
    "rc-tooltip": "^5.1.0",
```

Requiring an exact version prevents dependents from deduplicating if they don't also use exactly 5.1.0.

2021-04-26 19:50 UTC, bjyoungblood commented on src/common/Tooltip.tsx
> +        <HelpIcon color={"rgb(66, 153, 225"} />
```suggestion
        <HelpIcon color="rgb(66, 153, 225)" />
```

This might fix the fill color?

2021-04-27 00:46 UTC, tmadar commented on package.json
> +    "rc-tooltip": "5.1.0",
done

2021-04-27 00:46 UTC, tmadar commented on src/common/Tooltip.tsx
> +        <HelpIcon color={"rgb(66, 153, 225"} />
nope. pushed up the change to it though

2021-04-27 00:47 UTC, tmadar commented
@bjyoungblood 
> Looking good. I think you just need to run `yarn prettier --write ./src/**` and it'll get a ✅ from me!

done. thanks for the review and suggestions!

2021-04-27 16:34 UTC, bjyoungblood approved these changes

2021-05-23 15:29 UTC, merged