Eng: Rewrite
smartrent/badmagic pull request #59
Opened 2021-11-22 22:36 UTC by jwdotjs

For peer review of what I have so far

2021-11-29 00:05 UTC, mmiller42 commented on src/common/HistoricRecord.tsx
> +  }, [responseExpanded]);
```suggestion
  const toggleBodyExpanded = useCallback(() => {
    setBodyExpanded((e) => !e);
  }, []);
  const toggleResponseExpanded = useCallback(() => {
    setResponseExpanded((e) => !e);
  }, []);
```

2021-12-06 16:52 UTC, tscritch requested changes
Overall I'm really liking the changes! A few things:
- Can we remove all of the `@ts-ignore`s? 
- For the responses you have a lot of `null | sometype`. This is more preference but you could have the default response be undefined and change the typings to be `field?: type` like most of the other props. I get why you would do it either way so let me know what you think.
- I see just a few `any`s lying around that could be typed. It looks like you're aware of them but wanted to call it out. I'd like to see those typed.

Thanks for all the extra time you put into this Jason!

2021-12-06 16:52 UTC, tscritch commented on src/common/route/ApiError.tsx
> +      {error.response.data && isJSON && (
This would be really good to have HTML rendering since most of the need is from error responses.

2021-12-06 16:52 UTC, tscritch commented on src/common/History.tsx
> +  HistoryMetadata: undefined | HistoryMetadata;
```suggestion
  HistoryMetadata?: HistoryMetadata;
```

2021-12-06 16:52 UTC, tscritch commented on src/common/HistoricRecord.tsx
> +  HistoryMetadata: undefined | HistoryMetadata;
```suggestion
  HistoryMetadata?: HistoryMetadata;
```

2021-12-06 16:52 UTC, tscritch commented on src/lib/helpers.ts
> +  reduceDefaultParamValues(params: undefined | Param[]) {
```suggestion
  reduceDefaultParamValues(params?: Param[]) {
```

2021-12-06 16:52 UTC, tscritch commented on src/lib/helpers.ts
> +    workspace: undefined | Workspace;
```suggestion
    workspace?: Workspace;
```

2021-12-06 16:52 UTC, tscritch commented on src/common/route/Response.tsx
> +      <ApiError error={error as null | ApiErrorProp} />
Can these Prop types inherit from the axios types? I feel like we shouldn't have to cast these

2021-12-06 16:52 UTC, tscritch commented on src/types.ts
> +    status: number | undefined;
```suggestion
  code?: string;
  isAxiosError: boolean;
  response: {
    status?: number;
```

2021-12-06 16:52 UTC, tscritch commented on src/types.ts
> +    method: undefined | Method;
```suggestion
    method?: Method;
```

2021-12-06 16:52 UTC, tscritch commented on src/types.ts
> +  pathToValue: null | string;
This (and L172) could be made into `pathToValue?: string;` and will accomplish the same thing.

2021-12-06 16:54 UTC, tscritch commented on src/common/route/ApiError.tsx
> +      {error.response.data && isJSON && (
Which I know you will add my additions later but wanted to call out this file as an addition 👍🏻

2021-12-08 16:28 UTC, jwdotjs commented on src/common/route/ApiError.tsx
> +      {error.response.data && isJSON && (
Once I merge this, I can cleanup conflicts on your branch if any exist, we can merge that, and then we can tag

2021-12-08 16:29 UTC, jwdotjs commented on src/common/route/Response.tsx
> +      <ApiError error={error as null | ApiErrorProp} />
We can't because the historic records can be stored in local storage and when we store the json we aren't storing the entire AxiosResponse or AxiosError (which also has type definitions for functions that are built into it).

2021-12-08 18:22 UTC, tscritch commented
> Is `field?: type` the same as `null | sometype`? I thought `field?` means the value could be undefined, which I thought would be different, but maybe I've always misunderstood this 😆

If you didn't already get an explanation: 
`field?: type` === `field: type | undefined`
If you want null to be an option you have to explicitly specify that like `field: type | null`

What I was saying here: https://github.com/smartrent/badmagic/pull/59#discussion_r763187868
Is that because `undefined` and `null` behave the same in that use case you could make it `pathToValue?: string;` and have the style/format conform to the majority of the rest of the codebase.

2021-12-12 19:07 UTC, merged