i51: Deep Linking
smartrent/badmagic pull request #79
Opened 2022-10-07 00:46 UTC by jollyjerr

This PR adds support for copying a deep link to a request.

## Steps to test

1. Set up a request however you like (with a body/qsParams/etc...)
2. Click "Copy Link"
3. Paste that link in another browser
4. Observe you were "deep linked" to that request

## Video Demo

https://user-images.githubusercontent.com/51095001/194443085-4f466178-f435-4f66-8be8-c6808ae567ba.mov

2022-10-07 15:57 UTC, tscritch requested changes
Overall code looks amazing! Thanks so much for tackling this! One (hopefully) small thing. 

What do you think about putting the button either by the url or as the url? I had a hard time finding it and once I did it felt out of place.
Just an idea so feel free to disagree! haha
![Screen Shot 2022-10-07 at 10 56 18 AM](https://user-images.githubusercontent.com/11529600/194596678-f31ab9ed-bab6-415c-8753-a988ad696d8a.png)

2022-10-07 15:57 UTC, tscritch commented on src/lib/links.ts
> +    return `${window.location.origin}?request=${window.btoa(request)}`;
There's a problem when using this with CMW. Because we have BadMagic not on the origin path `localhost:4000/dev/api` this link does not work. It will redirect home.

What do you think about using `window.location.href`? 

Another option might be adding some way to configure this when setting up BadMagic.

2022-10-07 17:42 UTC, jollyjerr commented
Loved your design feedback @tscritch!

https://user-images.githubusercontent.com/51095001/194617721-89f58fc3-3b57-48d1-965f-8f0d72a51509.mov

2022-10-16 18:13 UTC, jwdotjs requested changes
When I tested on a route that had no activity, copying/pasting the link worked, but on a route where there were 1+ responses I got 414 Request URI Too Large.

<img width="1146" alt="Screen Shot 2022-10-16 at 11 02 28 AM" src="https://user-images.githubusercontent.com/246603/196051105-86f49c4b-d8e0-4ff9-a46d-7a70cf806943.png">

A few things that I noticed we were base64 encoding included markdown documentation for that route as well as request/response headers which could leak request headers (including auth headers). 

If we focused on this just being URL/QS/Body Params and the route name/id, this would probably be lighter weight and safer. What are your thoughts here?

It could be also be interesting to explore adding ReactRouter (now or in the future) as a peer dependency and let the router do the heavy lifting for figuring out which route we're on. We'd still need to figure out body params, but that would likely knock out the path, url params, and QS params all with pre-existing route matching support.

2022-10-17 02:24 UTC, jollyjerr commented
Hey @jwdotjs thank you for testing the upper bound of this approach. I initially considered porting the app over to react-router, but I think we can achieve the desired behavior without such a big shift at the moment. GREAT call out with the leaked security headers - I have to admit I was lazy with my approach and I didn't notice all that metadata was included 😨. How do you feel about these latest changes where only the required data is encoded? If we would rather port over to react-router instead of encoding the URI I'm down with that as well! We could also look into hashing the URI or various string-shortening techniques if size is still a concern.

2022-10-17 15:13 UTC, jwdotjs commented
Wow, thanks for the quick turnaround time. I was not expecting that! ❤️ 

I retested this morning and the URI size problem seems to be fixed and I think the type of data we're capturing all makes sense! 

I noticed that when I pasted the url, it seems to be not be loading the route definition correctly. If I get some free time today I'll try and see what might be causing that. 🙏 

## Route Definition With QS Params Specified
<img width="681" alt="Screen Shot 2022-10-17 at 8 09 27 AM" src="https://user-images.githubusercontent.com/246603/196214613-18c03ac9-eb77-4478-b7ad-11b0d8fbb440.png">

## Pasted URL 
<img width="298" alt="Screen Shot 2022-10-17 at 8 09 40 AM" src="https://user-images.githubusercontent.com/246603/196214622-e47cd44d-ac21-4144-9d25-7ecb40a393bf.png">

2023-04-07 14:56 UTC, jwdotjs commented
Sorry for the delay on this. I was thinking of integrating React Router so we can have more documentation, but I've been blocking this for too long 😆 

I'm going to look at the bug I posted in October, fix, and get this merged and tagged this weekend for us. 🙏 

cc: @briansmithSR

2023-07-19 21:06 UTC, justincy commented
If the current approach is too complicated, could we just go with the original idea of only deep linking to the route?

2023-07-25 15:01 UTC, jwdotjs commented
@justincy, yes, but this branch had bugs on it. I was working on it locally and I think it's in a better place, but I never had enough time to feel 100% confident. Let me push the updates to a branch targeting this branch for review

2023-07-25 15:05 UTC, jwdotjs commented
@justincy https://github.com/smartrent/badmagic/pull/90

2023-09-04 20:36 UTC, jollyjerr commented
Hey @jwdotjs and @justincy,

I took a look at #90 and pulled out the primary fix for route definitions not loading (thanks for finding that, Jason!). I also fixed a bug where actual requests would break after deep linking depending on if the project provided `baseURL` for route definitions. 

I think everything is good to go now. Let me know if you would like to see a video of a specific thing - I know setting this project up to test can be a hassle haha.

https://github.com/smartrent/badmagic/assets/51095001/3a8a313e-3aac-47b6-a288-4f34e696e0e7

https://github.com/smartrent/badmagic/assets/51095001/cc1e832d-4856-4246-b62b-3358b8f16a91

Invalid url just goes home

https://github.com/smartrent/badmagic/assets/51095001/749e9b02-f60c-48d4-90dc-0aad919c87b5

2023-09-08 16:46 UTC, merged